#!/bin/bash
set -e

source /docker-entrypoint-initdb.d/init.env

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $DB_USER WITH PASSWORD '$DB_USER_PASSWORD';

	CREATE DATABASE $DB_NAME;
	ALTER DATABASE $DB_NAME OWNER TO $DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
	GRANT USAGE, CREATE ON SCHEMA public TO $DB_USER;

    CREATE USER keycloak WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
    CREATE DATABASE keycloak_db;
	ALTER DATABASE keycloak_db OWNER TO keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO keycloak;
    GRANT USAGE, CREATE ON SCHEMA public TO keycloak;
EOSQL